### ISSUE TITLE
record archieving

### ISSUE THREAD

**Issue by ghost** [tangoshot/TangoShot#391]
Record versioning

You can use Auth to enable full record versioning:

db.enable_record_versioning(db,
    archive_db=None,
    archive_names='%(tablename)s_archive',
    current_record='current_record'):
This tells web2py to create an archive table for each of the tables in db and store a copy of each record when modified. The old copy is stored. The new copy is not.

The last three parameters are optional:

archive_db allows to specify another database where the archive tables are to be stored. Setting it to None is the same as setting it to db.
archive_names provides a pattern for naming each archive table.
current_record specified the name of the reference field to be used in the archive table to refer to the original, unmodified, record. Notice that archive_db!=db then the reference field is just an integer field since cross database references are not possible.
Only tables with modified_by and modified_on fields (as created for example by auth.signature) will be archived.

When you enable_record_versioning, if records have an is_active field (also created by auth.signature), records will never be deleted but they will be marked with is_active=False. In fact, enable_record_versioning adds a common_filter to every versioned table that filters out records with is_active=False so they essentially become invisible.

If you enable_record_versioning, you should not use auth.archive or crud.archive else you will end up with duplicate records. Those functions do explicitly what enable_record_versioning does automatically and they will be deprecated.

**Comment by tangoshot** [comment]
versioning is done. archiving is not crucial at the moment but I can have a separate ticket on that.
